name: Trigger Git Pull on Local Machine

on:
  push:
    branches:
      - main

jobs:
  ssh_trigger:
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
        chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key t-poo@82.64.214.121 -p 222 "cd T-POO-700-STG_12/ && git pull && docker compose -f docker-compose.prod.yml up --build"

    - name: Clean up
      run: rm private_key
